---
{
   "kind": "pipeline",
   "name": "default-amd64",
   "platform": {
      "arch": "amd64",
      "os": "linux"
   },
   "steps": [
      {
         "commands": [
            "mkdir ../build.rbldnsd",
            "cd ../build.rbldnsd",
            "cmake -DNO_IPv6=ON $DRONE_WORKSPACE",
            "make",
            "cd $DRONE_WORKSPACE",
            "mv ../build.rbldnsd/rbldnsd* .",
            "bash -c \"source /venv/bin/activate && robot test/functional/cases\"",
            "bash -c \"source /venv/bin/activate && python3 test/pyunit/tests.py\""
         ],
         "image": "rspamd/rbldnsd:build",
         "name": "test"
      }
   ],
   "trigger": {
      "event": {
         "include": [
            "push",
            "pull_request"
         ]
      }
   },
   "type": "docker"
}
---
{
   "kind": "pipeline",
   "name": "default-arm64",
   "platform": {
      "arch": "arm64",
      "os": "linux"
   },
   "steps": [
      {
         "commands": [
            "mkdir ../build.rbldnsd",
            "cd ../build.rbldnsd",
            "cmake -DNO_IPv6=ON $DRONE_WORKSPACE",
            "make",
            "cd $DRONE_WORKSPACE",
            "mv ../build.rbldnsd/rbldnsd* .",
            "bash -c \"source /venv/bin/activate && robot test/functional/cases\"",
            "bash -c \"source /venv/bin/activate && python3 test/pyunit/tests.py\""
         ],
         "image": "rspamd/rbldnsd:build",
         "name": "test"
      }
   ],
   "trigger": {
      "event": {
         "include": [
            "push",
            "pull_request"
         ]
      }
   },
   "type": "docker"
}
---
{
   "hmac": "6ee32e221e78ba085962f88df05d4424e4cd960933ff437276e8e65aecfa7322",
   "kind": "signature"
}
...
