---
kind: pipeline
type: docker
name: default

steps:
- name: test
  image: debian:bookworm
  commands:
  # TODO: create a build image...
  - apt-get update
  - apt-get install -y cmake g++ gcc libjemalloc-dev libev-dev make pkg-config python3-pip python3-venv zlib1g-dev
  - mkdir ../build.rbldnsd
  - cd ../build.rbldnsd
  # TODO: fix IPv6 in CI
  - cmake -DNO_IPv6=ON $DRONE_WORKSPACE
  - make
  - cd $DRONE_WORKSPACE
  - mv ../build.rbldnsd/rbldnsd* .
  - python3 -mvenv ~/venv
  - useradd rbldns
  - bash -c "source ~/venv/bin/activate && pip install py3dns robotframework"
  - bash -c "source ~/venv/bin/activate && robot test/functional/cases"
  - bash -c "source ~/venv/bin/activate && python3 test/pyunit/tests.py"

trigger:
  event:
    include:
      - push
      - pull_request
---
hmac: "ea322a06c11bdf2e1febb12a04b5ed04d6d7ea17c5c6f36dd9212f9e128f55a7"
kind: signature
...
